1

   Abaqus Learning Edition 2025                                  Date 28-jun-2026   Time 02:08:42
   

                                                                                 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        S T E P       1     C A L C U L A T I O N   O F   E I G E N V A L U E S

                                            F O R   B U C K L I N G   P R E D I C T I O N



                                                                                          

     THE SUBSPACE ITERATION METHOD IS USED FOR THIS ANALYSIS
     NUMBER OF EIGENVALUES                      1
     MAXIMUM NUMBER OF ITERATIONS                     50
     NUMBER OF VECTORS IN ITERATION                    3
     THE BUCKLING MODE CONSTRAINTS 
      ARE DEFINED AS LOAD CASE 2
                              ONLY INITIAL STRESS EFFECTS ARE INCLUDED IN THE
                              STIFFNESS MATRIX

     THIS IS A LINEAR PERTURBATION STEP.
     ALL LOADS ARE DEFINED AS CHANGE IN LOAD TO THE REFERENCE STATE

     EXTRAPOLATION WILL NOT BE USED

     CHARACTERISTIC ELEMENT LENGTH      29.6    

     DETAILS REGARDING ACTUAL SOLUTION WAVEFRONT REQUESTED

     DETAILED OUTPUT OF DIAGNOSTICS TO DATABASE REQUESTED

     PRINT OF INCREMENT NUMBER, TIME, ETC., TO THE MESSAGE FILE EVERY     1  INCREMENTS
 
	SYMMETRIC HYBRID DIRECT SPARSE SOLVER RUNNING ON
 	1 HOST x 1 MPI RANK PER HOST x 1 THREAD PER RANK
        NUMBER OF EQUATIONS:  2268
        NUMBER OF RHS:        1
        NUMBER OF FLOPS:      3.583e+07
        SOLVER ELAPSED TIME:  31ms
 
     ITERATION 1
      1       -6.255001e+03    
      2       -6.657970e+03    
      3       -7.313449e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 2
      1       -2.478667e+03    
      2       -3.658427e+03    
      3       -4.155193e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 3
      1       -1.645420e+03    
      2       -2.099159e+03    
      3       -2.422922e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 4
      1       -1.537485e+03    
      2       -1.719645e+03    
      3       -1.843926e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 5
      1       -1.515537e+03    
      2       -1.639009e+03    
      3       -1.685791e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 6
      1       -1.509533e+03    
      2       -1.607194e+03    
      3       -1.623671e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 7
      1       -1.507357e+03    
      2       -1.582957e+03    
      3       -1.594586e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 8
      1       -1.506381e+03    
      2       -1.563897e+03    
      3       -1.577357e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 9
      1       -1.505898e+03    
      2       -1.550579e+03    
      3       -1.563704e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 10
      1       -1.505640e+03    
      2       -1.541114e+03    
      3       -1.552261e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 11
      1       -1.505484e+03    
      2       -1.534183e+03    
      3       -1.542695e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 12
      1       -1.505370e+03    
      2       -1.528981e+03    
      3       -1.534823e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 13
      1       -1.505271e+03    
      2       -1.524967e+03    
      3       -1.528494e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 14
      1       -1.505177e+03    
      2       -1.521630e+03    
      3       -1.523693e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 15
      1       -1.505083e+03    
      2       -1.518360e+03    
      3       -1.520594e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 16
      1       -1.504992e+03    
      2       -1.515366e+03    
      3       -1.518635e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 17
      1       -1.504906e+03    
      2       -1.512930e+03    
      3       -1.517236e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 18
      1       -1.504826e+03    
      2       -1.511014e+03    
      3       -1.516196e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 19
      1       -1.504755e+03    
      2       -1.509527e+03    
      3       -1.515411e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 20
      1       -1.504694e+03    
      2       -1.508380e+03    
      3       -1.514818e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 21
      1       -1.504642e+03    
      2       -1.507498e+03    
      3       -1.514366e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 22
      1       -1.504600e+03    
      2       -1.506822e+03    
      3       -1.514023e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 23
      1       -1.504565e+03    
      2       -1.506305e+03    
      3       -1.513761e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 24
      1       -1.504537e+03    
      2       -1.505910e+03    
      3       -1.513562e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 25
      1       -1.504515e+03    
      2       -1.505609e+03    
      3       -1.513409e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 26
      1       -1.504497e+03    
      2       -1.505379e+03    
      3       -1.513292e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 27
      1       -1.504483e+03    
      2       -1.505204e+03    
      3       -1.513203e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 28
      1       -1.504472e+03    
      2       -1.505071e+03    
      3       -1.513134e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 29
      1       -1.504463e+03    
      2       -1.504969e+03    
      3       -1.513082e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 30
      1       -1.504456e+03    
      2       -1.504891e+03    
      3       -1.513042e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 31
      1       -1.504450e+03    
      2       -1.504832e+03    
      3       -1.513011e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 32
      1       -1.504445e+03    
      2       -1.504786e+03    
      3       -1.512987e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 33
      1       -1.504442e+03    
      2       -1.504751e+03    
      3       -1.512969e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 34
      1       -1.504439e+03    
      2       -1.504724e+03    
      3       -1.512955e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 35
      1       -1.504437e+03    
      2       -1.504703e+03    
      3       -1.512944e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 36
      1       -1.504435e+03    
      2       -1.504687e+03    
      3       -1.512936e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 37
      1       -1.504434e+03    
      2       -1.504674e+03    
      3       -1.512930e+03    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1


          THE ANALYSIS HAS BEEN COMPLETED



     ANALYSIS SUMMARY:
     TOTAL OF          1  INCREMENTS
                       0  CUTBACKS IN AUTOMATIC INCREMENTATION
                       1  ITERATIONS INCLUDING CONTACT ITERATIONS IF PRESENT
                       1  PASSES THROUGH THE EQUATION SOLVER OF WHICH 
                       1  INVOLVE MATRIX DECOMPOSITION, INCLUDING
                       0  DECOMPOSITION(S) OF THE MASS MATRIX
                       1  REORDERING OF EQUATIONS TO MINIMIZE WAVEFRONT
                       0  ADDITIONAL RESIDUAL EVALUATIONS FOR LINE SEARCHES
                       0  ADDITIONAL OPERATOR EVALUATIONS FOR LINE SEARCHES
                       0  WARNING MESSAGES DURING USER INPUT PROCESSING
                       0  WARNING MESSAGES DURING ANALYSIS
                       0  ANALYSIS WARNINGS ARE NUMERICAL PROBLEM MESSAGES
                       0  ANALYSIS WARNINGS ARE NEGATIVE EIGENVALUE MESSAGES
                       0  ERROR MESSAGES



     JOB TIME SUMMARY
       USER TIME (SEC)      =      1.1    
       SYSTEM TIME (SEC)    =     0.10    
       TOTAL CPU TIME (SEC) =      1.2    
       WALLCLOCK TIME (SEC) =            2
       MEMORY PEAK (GB)     =            0
